###################### SDK DRONE CI ######################
kind: pipeline
type: docker
name: default

trigger:
  event: push

steps:
  - name: install
    image: node:18.19
    pull: always
    commands:
      # TODO: remove when drone plugin is live
      - cd packages/sdk
      - node -v
      - npm -v
      - npm ci

  - name: format
    image: node:18.19
    commands:
      # TODO: remove when drone plugin is live
      - cd packages/sdk
      - npm run check-format

  - name: lint
    image: node:18.19
    commands:
      # TODO: remove when drone plugin is live
      - cd packages/sdk
      - npm run lint

  - name: check-types
    image: node:18.19
    commands:
      # TODO: remove when drone plugin is live
      - cd packages/sdk
      - npm run check-types

  - name: test
    image: node:18.19
    commands:
      # TODO: remove when drone plugin is live
      - cd packages/sdk
      - npm run test

  - name: build
    image: node:18.19
    commands:
      # TODO: remove when drone plugin is live
      - cd packages/sdk
      - npm run build

  - name: npm publish dry-run
    image: node:18.19
    commands:
      # TODO: remove when drone plugin is live
      - cd packages/sdk
      - npm publish --dry-run

---
kind: pipeline
type: docker
name: publish npm nightly

trigger:
  event:
    - promote
  target:
    - nightly
  branch:
    - develop

steps:
  - name: install
    image: node:18.19
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: format
    image: node:18.19
    commands:
      - npm run check-format

  - name: lint
    image: node:18.19
    commands:
      - npm run lint

  - name: check-types
    image: node:18.19
    commands:
      - npm run check-types

  - name: test
    image: node:18.19
    commands:
      - npm run test

  - name: build
    image: node:18.19
    commands:
      - npm run build

  - name: set version nightly
    image: node:18.19
    commands:
      - eval npm pkg set version="$(npm pkg get version)-nightly-$DRONE_COMMIT"

  - name: npm publish
    image: plugins/npm
    settings:
      username:
        from_secret: npm_username
      token:
        from_secret: npm_token
      tag: nightly
      access: public

---
kind: pipeline
type: docker
name: publish npm latest

trigger:
  event:
    - promote
  target:
    - latest
  branch:
    - main

steps:
  - name: install
    image: node:18.19
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: format
    image: node:18.19
    commands:
      - npm run check-format

  - name: lint
    image: node:18.19
    commands:
      - npm run lint

  - name: check-types
    image: node:18.19
    commands:
      - npm run check-types

  - name: test
    image: node:18.19
    commands:
      - npm run test

  - name: build
    image: node:18.19
    commands:
      - npm run build

  - name: npm publish
    image: plugins/npm
    settings:
      username:
        from_secret: npm_username
      token:
        from_secret: npm_token
      tag: latest
      access: public
---
kind: pipeline
type: docker
name: deprecate-version

trigger:
  event:
    - promote
  target:
    - npm-deprecate-package

steps:
  - name: authenticate
    image: robertstettner/drone-npm-auth
    settings:
      username:
        from_secret: npm_username
      token:
        from_secret: npm_token

  - name: deprecate package
    image: node:18.19
    params:
      - PACKAGE_VERSION
    commands:
      - if [ -n "$PACKAGE_VERSION" ]; then npm deprecate @iexec/dataprotector@$PACKAGE_VERSION "deprecate $PACKAGE_VERSION"; else echo "PACKAGE_VERSION is not set"; fi
---
kind: pipeline
type: docker
name: undeprecate version

trigger:
  event:
    - promote
  target:
    - npm-undeprecate-package

steps:
  - name: authenticate
    image: robertstettner/drone-npm-auth
    settings:
      username:
        from_secret: npm_username
      token:
        from_secret: npm_token

  - name: undeprecate package
    image: node:18.19
    params:
      - PACKAGE_VERSION
    commands:
      - if [ -n "$PACKAGE_VERSION" ]; then npm deprecate @iexec/dataprotector@$PACKAGE_VERSION ""; else echo "PACKAGE_VERSION is not set"; fi

###################### SMART CONTRACT DRONE CI ######################
kind: pipeline
type: docker
name: smart-contract-default

trigger:
  event:
    exclude:
      - promote

steps:
  - name: install deps
    image: node:18.19
    pull: always
    commands:
      - node -v
      - npm -v
      - cd Smart_Contract
      - npm ci

  - name: check format
    image: node:18.19
    commands:
      - cd Smart_Contract
      - npm run check-format

  - name: check lint
    image: node:18.19
    commands:
      - cd Smart_Contract
      - npm run lint

  - name: compile smart contracts
    image: node:18.19
    commands:
      - cd Smart_Contract
      - npm run compile

  - name: test smart contracts
    image: node:18.19
    commands:
      - cd Smart_Contract
      - npm run test

  - name: dry-deployment smart-contract
    image: node:18.19
    commands:
      - cd Smart_Contract
      - npm run deploy
      - cat .smart-contract-address

---
# deploy smart contract in prod or dev
kind: pipeline
type: docker
name: deploy smart contract

trigger:
  event:
    - promote
  target:
    - smart-contract-dev
    - smart-contract-production
  branch:
    - develop
    - main

steps:
  - name: install deps
    image: node:18.19
    pull: always
    commands:
      - node -v
      - npm -v
      - cd Smart_Contract
      - npm ci

  - name: check format
    image: node:18.19
    commands:
      - cd Smart_Contract
      - npm run check-format

  - name: check lint
    image: node:18.19
    commands:
      - cd Smart_Contract
      - npm run lint

  - name: compile smart contracts
    image: node:18.19
    commands:
      - cd Smart_Contract
      - npm run compile

  - name: test smart contracts
    image: node:18.19
    commands:
      - cd Smart_Contract
      - npm run test

  - name: smart-contract dev deployment
    image: node:18.19
    environment:
      WALLET_PRIVATE_KEY:
        from_secret: deployer-dev-privatekey
    commands:
      - cd Smart_Contract
      - npm run deploy -- --network bellecour
      - cat .smart-contract-address
    when:
      target:
        - smart-contract-dev
      branch:
        - develop

  - name: smart-contract prod deployment
    image: node:18.19
    environment:
      WALLET_PRIVATE_KEY:
        from_secret: deployer-prod-privatekey
    commands:
      - cd Smart_Contract
      - npm run deploy -- --network bellecour
      - cat .smart-contract-address
    when:
      target:
        - smart-contract-production
      branch:
        - main

  # TODO: Adapt/delete this verification step according with the new dev environment
  - name: verify dev contract
    image: node:18.19
    commands:
      - cd Smart_Contract
      - npm run verify -- --network bellecour $(cat .smart-contract-address) $(cat .constructor-args-params)
    when:
      target:
        - smart-contract-dev
      branch:
        - develop

  - name: verify prod contract
    image: node:18.19
    commands:
      - cd Smart_Contract
      - npm run verify -- --network bellecour $(cat .smart-contract-address) $(cat .constructor-args-params)
    when:
      target:
        - smart-contract-production
      branch:
        - main
# TODO: add a last step to add the dev ens or prod ens on the deployed SC address

###################### SUBGRAPH DRONE CI ######################
kind: pipeline
type: docker
name: subgraph-default

trigger:
  event:
    exclude:
      - promote

steps:
  - name: build-subgraph
    image: node:18.19
    commands:
      - cd Subgraph
      - npm ci
      - npm run codegen
      - npm run build

---
kind: pipeline
type: docker
name: deploy-subgraph-dev

trigger:
  event:
    - promote
  target:
    - subgraph-dev
  branch:
    - develop

steps:
  - name: deploy
    image: node:18.19
    params:
      - START_BLOCK
    environment:
      GRAPHNODE_URL:
        from_secret: graphnode-url
      IPFS_URL:
        from_secret: ipfs-url
    commands:
      - export SUBGRAPH_NAME=bellecour/dev-dataprotector
      - echo "deploying commit $DRONE_COMMIT on subgraph $SUBGRAPH_NAME"
      - cd Subgraph
      - npm ci
      - npm run codegen
      - npm run build
      - npx graph create --node $GRAPHNODE_URL $SUBGRAPH_NAME
      - npx graph deploy --node $GRAPHNODE_URL $SUBGRAPH_NAME --ipfs $IPFS_URL --version-label $DRONE_COMMIT

---
kind: pipeline
type: docker
name: deploy-subgraph-production

trigger:
  event:
    - promote
  target:
    - subgraph-production
  branch:
    - main

steps:
  - name: deploy
    image: node:18.19
    params:
      - START_BLOCK
    environment:
      GRAPHNODE_URL:
        from_secret: graphnode-url
      IPFS_URL:
        from_secret: ipfs-url
    commands:
      - export SUBGRAPH_NAME=bellecour/dataprotector
      - echo "deploying commit $DRONE_COMMIT on subgraph $SUBGRAPH_NAME"
      - cd Subgraph
      - npm ci
      - npm run codegen
      - npm run build
      - npx graph create --node $GRAPHNODE_URL $SUBGRAPH_NAME
      - npx graph deploy --node $GRAPHNODE_URL $SUBGRAPH_NAME --ipfs $IPFS_URL --version-label $(npm pkg get version)

