kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:18
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci
      - npm run build
  - name: test
    image: node:18
    pull: always
    commands:
      - npm run test
