kind: pipeline
type: docker
name: default

trigger:
  event:
    exclude:
      - promote

steps:
  - name: install
    image: node:18
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: test
    image: node:18
    pull: always
    commands:
      - npm run test

  - name: build
    image: node:18
    pull: always
    commands:
      - npm run build

---
kind: pipeline
type: docker
name: publish-nightly

trigger:
  event:
    - promote
  target:
    - nightly

steps:
  - name: install
    image: node:18
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: test
    image: node:18
    pull: always
    commands:
      - npm run test

  - name: build
    image: node:18
    pull: always
    commands:
      - npm run build

  - name: set-version-nightly
    image: node:18
    pull: always
    commands:
      - eval npm pkg set version="$(npm pkg get version)-nightly-$DRONE_COMMIT"

  - name: publish-dry-run
    image: node:18
    pull: always
    commands:
      - npm publish --tag nightly --dry-run

  - name: publish
    image: plugins/npm
    settings:
      username:
        from_secret: npm_username
      token:
        from_secret: npm_password
    # when:
    #   branch:
    #   - develop
