kind: pipeline
type: docker
name: default

trigger:
  event:
    exclude:
      - promote

steps:
  - name: install
    image: node:18
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: test
    image: node:18
    pull: always
    commands:
      - npm run test

  - name: build
    image: node:18
    pull: always
    commands:
      - npm run build

---
kind: pipeline
type: docker
name: publish-nightly

trigger:
  event:
    - promote
  target:
    - nightly

steps:
  - name: install
    image: node:18
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: test
    image: node:18
    pull: always
    commands:
      - npm run test

  - name: build
    image: node:18
    pull: always
    commands:
      - npm run build

  - name: publish-nightly-dry-run
    image: node:18
    pull: always
    commands:
      - eval npm pkg set version="$(npm pkg get version)-nightly-$DRONE_COMMIT"
      - npm publish --tag nightly --dry-run
